tests: Handle invalid PDFs
If you're missing things like Inkscape, PyMuPDF can fail with errors
like so:

  mupdf: cannot recognize version marker
  mupdf: no objects found
  Traceback (most recent call last):
    ...
  RuntimeError: no objects found

Handle this so the giant traceback doesn't bubble up to the user.

Signed-off-by: Stephen Finucane <stephen@that.guru>